### ISSUE TITLE
Crash when generating chunks (with updated NEX/LEX)

### ISSUE THREAD

**Issue by flamechair** [LogicTechCorp/NetherEx-Archive#108]
Hi,

I've seen a few other issues about chunk generating and the solution seems to be updating to the latest NEX/LEX. I've done that and I'm still experiencing crashes:

```
java.lang.NullPointerException: Exception ticking world
	at nex.world.gen.ChunkGeneratorNether.func_185931_b(ChunkGeneratorNether.java:411)
	at org.spongepowered.mod.world.gen.SpongeChunkGeneratorForge.func_185931_b(SpongeChunkGeneratorForge.java:269)
	at net.minecraft.world.chunk.Chunk.func_186034_a(Chunk.java:1017)
	at net.minecraft.world.chunk.Chunk.func_186030_a(Chunk.java:978)
	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:157)
	at net.minecraft.world.World.func_72964_e(World.java:309)
	at net.minecraft.server.management.PlayerChunkMapEntry.handler$resendUpdatedBiomes$zjl000(PlayerChunkMapEntry.java:554)
	at net.minecraft.server.management.PlayerChunkMapEntry.func_187280_d(PlayerChunkMapEntry.java)
	at net.minecraft.server.management.PlayerChunkMap.func_72693_b(SourceFile:108)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:227)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:756)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:748)
```

Full crash log: https://gist.github.com/iamtpage/dfddb62bba63d9e8648c8b2daf713300

NEX: 2.0.3
LEX: 1.0.3

**Comment by LogicTechCorp** [comment]
This issue has been fixed in the latest release.
