### ISSUE TITLE
Game Crash when Right-Clicking Zombie Pigman (baby)

### ISSUE THREAD

**Issue by Zarepheth** [LogicTechCorp/NetherEx-Archive#114]
As the title says, the game crashes when I right-click a baby zombie pigman in the Nether.

Here's the top of the stack trace:
```
[23:05:48] [main/FATAL] [minecraft/Minecraft]: Unreported exception thrown!
java.lang.IllegalArgumentException: Invalid hand null
	at net.minecraft.entity.EntityLivingBase.func_184586_b(EntityLivingBase.java:1633) ~[vp.class:?]
	at nex.handler.ClickHandler.onPlayerEntityInteract(ClickHandler.java:197) ~[ClickHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_394_ClickHandler_onPlayerEntityInteract_EntityInteract.invoke(.dynamic) ~[?:?]
```
And full details on [Paste.ee](https://paste.ee/p/UVIk0#s=0)

There's a fair chance that this is caused by a conflict with another mod. Initially, I thought the Thaumcraft "thaumometer" was the cause because the first two crashes occurred when attempting to register the baby zombie pigman as "observed" in Thaumcraft. However, Thaumcraft was nowhere to be found in the stack trace - so I simply tried a right-click while holding some toast in my hand. I got the same crash.

**Comment by LogicTechCorp** [comment]
This issue has been fixed in the latest version.

**Comment by Zarepheth** [comment]
Thanks!
I had no crashes when right-clicking Zombie Pigmen (adult or baby) with an equiped Thaumometer while using the latest version.

**Comment by LogicTechCorp** [comment]
No problem, thank you for reporting the bug.
