### ISSUE TITLE
Crash After Joining Nether

### ISSUE THREAD

**Issue by znxster** [LogicTechCorp/NetherEx-Archive#184]
Modpack: Roguelike Adventures and Dungeons
Version: 1.2.9
Minecraft Version: 1.12.2
Forge: 14.23.5.2838
NetherEx: 1.12.2-2.0.10

I am playing on the R.A.D. modpack and it pointed me to  NetherEx as a possible cause of the crash and linked to [hastebin](https://paste.dimdev.org/efasicikub.mccrash) for the crash report.

This was my first time entering the Nether, I was able to join. Mined some soul sand and then my shovel hit "gloomy netherack", at which point it crashed.

Brief of crash report:
```
---- Minecraft Crash Report ----
// I blame LogicTechCorp.

Time: 2019-08-24 23:19:58 BST
Description: Unexpected error

java.lang.NullPointerException
    at logictechcorp.netherex.block.BlockNetherrack.onBlockClicked(BlockNetherrack.java:61)
    at net.minecraft.client.multiplayer.PlayerControllerMP.clickBlock(PlayerControllerMP.java:242)
    at net.minecraft.client.multiplayer.PlayerControllerMP.onPlayerDamageBlock(PlayerControllerMP.java:334)
    at net.minecraft.client.Minecraft.sendClickBlockToController(Minecraft.java:1480)
    at net.minecraft.client.Minecraft.processKeyBinds(Minecraft.java:2268)
    at net.minecraft.client.Minecraft.runTickKeyboard(Minecraft.java:2020)
    at net.minecraft.client.Minecraft.runTick(Minecraft.java:1808)
    at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1098)
    at net.minecraft.client.Minecraft.run(Minecraft.java:3942)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
```

**Comment by LogicTechCorp** [comment]
This has been fixed in the latest version.
