### ISSUE TITLE
NetherEX crash when loaded with Biomes 'o' Plenty Mod

### ISSUE THREAD

**Issue by TsundereTechSupport** [LogicTechCorp/NetherEx-Archive#248]
[https://pastebin.com/GzZdEpyR](url)
---- Minecraft Crash Report ----
// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 8/10/20 1:25 PM
Description: Initializing game

java.lang.NullPointerException: Registry Object not present: netherex:spore_creeper_explosion
	at java.util.Objects.requireNonNull(Objects.java:290) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.RegistryObject.get(RegistryObject.java:120) ~[?:?] {re:classloading}
	at logictechcorp.netherex.proxy.ClientProxy.onRegisterParticleFactory(ClientProxy.java:75) ~[?:4.0.0] {re:classloading}
	at logictechcorp.netherex.proxy.ClientProxy$$Lambda$2292/1290517394.accept(Unknown Source) ~[?:?] {}
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:212) ~[eventbus-2.2.0-service.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:204) ~[eventbus-2.2.0-service.jar:?] {}
	at net.minecraftforge.eventbus.EventBus$$Lambda$2077/131582664.invoke(Unknown Source) ~[?:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258) ~[eventbus-2.2.0-service.jar:?] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:168) ~[?:31.2] {re:classloading}
	at net.minecraftforge.fml.ModLoader.lambda$postEvent$31(ModLoader.java:260) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.ModLoader$$Lambda$2809/1548269356.accept(Unknown Source) ~[?:?] {}
	at java.util.HashMap.forEach(HashMap.java:1280) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.ModList.forEachModContainer(ModList.java:218) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.ModLoader.postEvent(ModLoader.java:260) ~[?:?] {re:classloading}
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:437) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(SourceFile:166) [?:?] {re:classloading}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.15.2-31.2.36.jar:31.2] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$419/2108318195.call(Unknown Source) [forge-1.15.2-31.2.36.jar:31.2] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-5.1.2.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-5.1.2.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-5.1.2.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81) [modlauncher-5.1.2.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-5.1.2.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at java.util.Objects.requireNonNull(Objects.java:290)
	at net.minecraftforge.fml.RegistryObject.get(RegistryObject.java:120)
	at logictechcorp.netherex.proxy.ClientProxy.onRegisterParticleFactory(ClientProxy.java:75)
	at logictechcorp.netherex.proxy.ClientProxy$$Lambda$2292/1290517394.accept(Unknown Source)
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:212)
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:204)
	at net.minecraftforge.eventbus.EventBus$$Lambda$2077/131582664.invoke(Unknown Source)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258)
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:168)
	at net.minecraftforge.fml.ModLoader.lambda$postEvent$31(ModLoader.java:260)
	at net.minecraftforge.fml.ModLoader$$Lambda$2809/1548269356.accept(Unknown Source)
	at java.util.HashMap.forEach(HashMap.java:1280)
	at net.minecraftforge.fml.ModList.forEachModContainer(ModList.java:218)
	at net.minecraftforge.fml.ModLoader.postEvent(ModLoader.java:260)
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:437)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.main.Main.main(SourceFile:166)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$419/2108318195.call(Unknown Source)
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81)
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65)

-- System Details --
Details:
	Minecraft Version: 1.15.2
	Minecraft Version ID: 1.15.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 5695927840 bytes (5432 MB) / 6442450944 bytes (6144 MB) up to 6442450944 bytes (6144 MB)
	CPUs: 8
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx6G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 5.1.2+70+master.2845bb9
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/eventbus-2.2.0-service.jar eventbus PLUGINSERVICE 
		/forge-1.15.2-31.2.36.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.15.2-31.2.36.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-2.1.3-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.15.2-31.2.36.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.15.2-31.2.36.jar runtimedistcleaner PLUGINSERVICE 
		/forge-1.15.2-31.2.36.jar fml TRANSFORMATIONSERVICE 
	FML: 31.2
	Forge: net.minecraftforge:31.2.36
	FML Language Providers: 
		javafml@31.2
		minecraft@1
	Mod List: 
		forge-1.15.2-31.2.36-client.jar Minecraft {minecraft@1.15.2 LOAD_REGISTRIES}
		inventorysorter-1.15.2-17.0.0.jar Simple Inventory Sorter {inventorysorter@17.0.0 LOAD_REGISTRIES}
		DungeonCrawl-1.15.2-1.6.3.jar Dungeon Crawl {dungeoncrawl@1.6.3 LOAD_REGISTRIES}
		BiomesOPlenty-1.15.2-10.0.0.345-universal.jar Biomes O' Plenty {biomesoplenty@1.15.2-10.0.0.342 ERROR}
		vanilladeathchest-1.15.2-1.10.3.8.jar VanillaDeathChest {vanilladeathchest@1.15.2-1.10.3.8 LOAD_REGISTRIES}
		jei-1.15.2-6.0.0.3.jar Just Enough Items {jei@6.0.0.3 LOAD_REGISTRIES}
		FallingTree-1.15.2-2.1.0+24.jar Falling Tree {falling_tree@2.1.0+24 LOAD_REGISTRIES}
		XL-Food-Mod-1.15.2-2.2.2.jar XL Food Mod {xlfoodmod@2.2.2 LOAD_REGISTRIES}
		mcw-windows-1.0.1-mc1.15.2_1.15.1.jar Macaw's Windows {mcwwindows@1.0.1 LOAD_REGISTRIES}
		forge-1.15.2-31.2.36-universal.jar Forge {forge@31.2.36 LOAD_REGISTRIES}
		Aquaculture-1.15.2-2.0.13.jar Aquaculture 2 {aquaculture@1.15.2-2.0.13 LOAD_REGISTRIES}
		Xaeros_Minimap_20.19.0_Forge_1.15.2.jar Xaero's Minimap {xaerominimap@20.19.0 LOAD_REGISTRIES}
		NetherEx-1.15.2-4.0.0.jar NetherEx {netherex@4.0.0 LOAD_REGISTRIES}
		LibraryEx-1.15.2-3.0.0.jar LibraryEx {libraryex@3.0.0 LOAD_REGISTRIES}
	Launched Version: 1.15.2-forge-31.2.36
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: GeForce GTX 1080 Ti/PCIe/SSE2 GL version 4.6.0 NVIDIA 432.00, NVIDIA Corporation
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	CPU: 8x Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz

![MineCraftCrash](https://user-images.githubusercontent.com/69483984/89830021-680f1500-db10-11ea-8e7e-6ee3de8e6e19.png)

**Comment by LogicTechCorp** [comment]
This issue has been fixed in the latest version.
