### ISSUE TITLE
Ticking Entity Crash / Animania Compatibility Issue

### ISSUE THREAD

**Issue by HootlingMC** [LogicTechCorp/NetherEx-Archive#30]
There is some kind of compatibility issue with NetherEx and Animania.
https://github.com/capnkirok/animania

EDIT: https://github.com/capnkirok/animania/issues/275 

When both are installed, I end up getting a ticking entity crash, seemingly with an Animania mob (piglet) but it only happens when NetherEx is installed.   Same map, same location does not crash if NetherEx is disabled.

Crash Log:
---- Minecraft Crash Report ----

WARNING: coremods are present:
Contact their authors BEFORE contacting forge

// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 7/20/17 1:37 PM
Description: Ticking entity

java.lang.NullPointerException: Ticking entity
	at nex.handler.EventHandler.onLivingUpdate(EventHandler.java:407)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_31_EventHandler_onLivingUpdate_LivingUpdateEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185)
	at net.minecraftforge.common.ForgeHooks.onLivingUpdate(ForgeHooks.java:531)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2005)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:384)
	at net.minecraft.world.World.func_72866_a(World.java:1965)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:840)
	at net.minecraft.world.World.func_72870_g(World.java:1934)
	at net.minecraft.world.World.func_72939_s(World.java:1748)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:621)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:720)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:624)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:240)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:482)
	at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at nex.handler.EventHandler.onLivingUpdate(EventHandler.java:407)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_31_EventHandler_onLivingUpdate_LivingUpdateEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185)
	at net.minecraftforge.common.ForgeHooks.onLivingUpdate(ForgeHooks.java:531)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2005)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:384)
	at net.minecraft.world.World.func_72866_a(World.java:1965)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:840)
	at net.minecraft.world.World.func_72870_g(World.java:1934)

-- Entity being ticked --
Details:
	Entity Type: null (com.animania.common.entities.pigs.EntityPigletBase)
	Entity ID: 4982
	Entity Name: unknown
	Entity's Exact location: -179.50, 70.00, -256.50
	Entity's Block location: World: (-180,70,-257), Chunk: (at 12,4,15 in -12,-17; contains blocks -192,0,-272 to -177,255,-257), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Entity's Momentum: 0.00, 0.00, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1748)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:621)

-- Affected level --
Details:
	Level name: Copy of New World-
	All players: 1 total; [EntityPlayerMP['Hootling'/1277, l='Copy of New World-', x=-104.64, y=90.40, z=-167.10]]
	Chunk stats: ServerChunkCache: 532 Drop: 0
	Level seed: -6615956970526181320
	Level generator: ID 00 - default, ver 1. Features enabled: true
	Level generator options: 
	Level spawn location: World: (36,64,24), Chunk: (at 4,4,8 in 2,1; contains blocks 32,0,16 to 47,255,31), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 601 game time, 601 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 58151 (now: false), thunder time: 155501 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:720)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:624)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:240)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:482)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.11.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 811956224 bytes (774 MB) / 2516058112 bytes (2399 MB) up to 5726797824 bytes (5461 MB)
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx6144m -Xms256m -XX:PermSize=256m
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP 9.38 Powered by Forge 13.20.1.2414 Optifine OptiFine_1.11.2_HD_U_B9 7 mods loaded, 7 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	minecraft{1.11.2} [Minecraft] (minecraft.jar) 
	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.11.2-13.20.1.2414.jar) 
	UCHIJAAAA	forge{13.20.1.2414} [Minecraft Forge] (forge-1.11.2-13.20.1.2414.jar) 
	UCHIJAAAA	craftstudioapi{0.3.0-beta} [CraftStudio API] (CraftStudioAPI-universal-0.3.0.86-mc1.11.2-beta.jar) 
	UCHIJAAAA	animania{1.2.1} [Animania] (animania-1.11.2-1.2.1.jar) 
	UCHIJAAAA	nex{1.1.7.8} [NetherEx] (NetherEx-1.11.2-1.1.7.8.jar) 
	Loaded coremods (and transformers): 
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Profiler Position: N/A (disabled)
	Player Count: 1 / 8; [EntityPlayerMP['Hootling'/1277, l='Copy of New World-', x=-104.64, y=90.40, z=-167.10]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	OptiFine Version: OptiFine_1.11.2_HD_U_B9
	Render Distance Chunks: 8
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.5.0 NVIDIA 382.05
	OpenGlRenderer: GeForce GTX 980M/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 8

**Comment by LogicTechCorp** [comment]
This should be fixed in the latest version.
