### ISSUE TITLE
The "Trade Lists" directory in "config/NetherEx" is not automatically created on some platforms

### ISSUE THREAD

**Issue by asiekierka** [LogicTechCorp/NetherEx-Archive#62]
Creating the directory manually resolves the following crash report:

[21:18:29] [main/INFO]: [net.minecraft.init.Bootstrap:printToSYSOUT:630]: ---- Minecraft Crash Report ----

WARNING: coremods are present:
  LoadingPlugin (Quark-r1.3-117.jar)
  CTMCorePlugin (CTM-MC1.12-0.2.2.7.jar)
Contact their authors BEFORE contacting forge

// I just don't know what went wrong :(

Time: 11/30/17 9:18 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from NetherEx (nex)
Caused by: java.lang.NullPointerException
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:770)
	at com.google.common.collect.Lists.newArrayList(Lists.java:112)
	at nex.village.TradeManager.init(TradeManager.java:80)
	at nex.NetherEx.onFMLInitialization(NetherEx.java:87)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:608)
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:253)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:231)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:148)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:719)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:352)
	at net.minecraft.client.Minecraft.init(Minecraft.java:581)
	at net.minecraft.client.Minecraft.run(Minecraft.java:421)
	at net.minecraft.client.main.Main.main(Main.java:118)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraftforge.gradle.GradleStartCommon.launch(GradleStartCommon.java:97)
	at GradleStart.main(GradleStart.java:26)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Linux (amd64) version 4.14.2_1
	Java Version: 1.8.0_172, Oracle Corporation
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 375310696 bytes (357 MB) / 890241024 bytes (849 MB) up to 1377828864 bytes (1314 MB)
	JVM Flags: 0 total; 
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.0.2549 10 mods loaded, 10 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                   | Version          | Source                           | Signature |
	|:----- |:-------------------- |:---------------- |:-------------------------------- |:--------- |
	| UCHI  | minecraft            | 1.12.2           | minecraft.jar                    | None      |
	| UCHI  | mcp                  | 9.42             | minecraft.jar                    | None      |
	| UCHI  | FML                  | 8.0.99.99        | forgeSrc-1.12.2-14.23.0.2549.jar | None      |
	| UCHI  | forge                | 14.23.0.2549     | forgeSrc-1.12.2-14.23.0.2549.jar | None      |
	| UCHI  | unlimitedchiselworks | ${version}       | UnlimitedChiselWorks             | None      |
	| UCHI  | chisel               | MC1.12-0.0.14.18 | Chisel-MC1.12-0.0.14.18.jar      | None      |
	| UCHI  | ctm                  | MC1.12-0.2.2.7   | CTM-MC1.12-0.2.2.7.jar           | None      |
	| UCHI  | quark                | r1.3-117         | Quark-r1.3-117.jar               | None      |
	| UCHI  | autoreglib           | 1.3-15           | AutoRegLib-1.3-15.jar            | None      |
	| UCHE  | nex                  | 2.1.12.13        | NetherEx-1.12-2.1.12.13.jar      | None      |

	Loaded coremods (and transformers): 
LoadingPlugin (Quark-r1.3-117.jar)
  vazkii.quark.base.asm.ClassTransformer
CTMCorePlugin (CTM-MC1.12-0.2.2.7.jar)
  team.chisel.ctm.client.asm.CTMTransformer
	GL info: ' Vendor: 'Intel Open Source Technology Center' Version: '3.0 Mesa 17.2.6' Renderer: 'Mesa DRI Intel(R) Sandybridge Mobile '
[21:18:29] [main/INFO]: [net.minecraft.init.Bootstrap:printToSYSOUT:630]: #@!@# Game crashed! Crash report saved to: #@!@# /home/asie/UnlimitedChiselWorks/run/./crash-reports/crash-2017-11-30_21.18.29-client.txt
Disconnected from the target VM, address: '127.0.0.1:35531', transport: 'socket'

**Comment by LogicTechCorp** [comment]
This issue should be resolved in the latest release.
